export enum AdminUrls {
  LOGIN_PAGE = '/admin/login',
  ADMIN_REROUTE_PAGE = '/admin/dashboard',
  DASHBOARD_PAGE = 'dashboard',
  INVENTORY_PAGE = 'inventory',
  PRODUCT_PAGE = 'inventory/product',
  PRODUCT_CREATE_PAGE = 'create',
  ORDER_PAGE = 'inventory/orders',
  CONFIGURATION_URL = 'configuration',
  GENERAL_PAGE = 'configuration/general',
  TEMPLATE_PAGE = 'configuration/template',
  HEADER_PAGE = 'configuration/header',
  THEME_PAGE = 'configuration/theme',
  FOOTER_PAGE = 'configuration/footer',
  PAGE_URL = 'pages',
  HOME_PAGE = 'pages/home-page',
  HOME_PAGE_EDIT = 'edit/:id',
}
